[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
itertools = "0.10.1"
scan-rules = "0.2.0"
recap = "0.1.1"
serde = "1.0.130"